hw2
agarkovv/system-design-sbt pull request #2
Opened 2024-11-05 19:15 UTC by agarkovv

2024-11-25 15:35 UTC, Smartslame requested changes

2024-11-25 15:35 UTC, Smartslame commented on hw2-ansible/deploy.yml
> +  tasks:
Кажется ты неправильно понял задание :(

Цель домашки - научиться пользоваться ансимблом, а докер предлагалось использовать за неимением чистых машин, на котором что-либо должен делать ансибл.

То есть у тебя есть чистая машина (например alpine контейнер без ничего или пустая VDSка), ты подключаешься к ней ансиблом и устанавливаешь нужные либы, питон, скачиваешь свою приложуху с гита, запускаешь ее. Ну и все в таком духе.

2024-12-07 19:21 UTC, agarkovv commented on hw2-ansible/deploy.yml
> +  tasks:
Пофиксил

2024-12-13 17:24 UTC, Smartslame approved these changes

2024-12-14 18:55 UTC, merged